### ISSUE TITLE
网易云音乐地址泄露

### ISSUE THREAD

**Issue by RINZE1** [SunsetMkt/anti-ip-attribution#70]
暂时发现以下IP和域名会导致泄露，可能待补充
DOMAIN,interface3.music.163.com.163jiasu.com
IP-CIDR,119.36.90.80/32
IP-CIDR,111.48.137.146/32
IP-CIDR,1.95.21.35/32
IP-CIDR,47.100.127.239/32

**Comment by SunsetMkt** [comment]
感谢

https://github.com/SunsetMkt/anti-ip-attribution/commit/221b8c6ffc6efb9a9d59b8d04f075a87031a41a2
